/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current session (user is null when signed out). Also issues the CSRF cookie. */
        get: operations["AuthController_session_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/csrf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return the CSRF token, issuing the cookie if needed. */
        get: operations["AuthController_csrfToken_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an account. Always accepted; a confirmation e-mail follows. */
        post: operations["AuthController_register_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm an e-mail address with the e-mailed token and sign in. */
        post: operations["AuthController_verifyEmail_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/verify-email/resend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_resendVerification_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign in with e-mail and password. */
        post: operations["AuthController_login_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_logout_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password/forgot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_forgotPassword_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_resetPassword_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password/change": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_changePassword_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Signed-in devices of the current user. */
        get: operations["AuthController_listSessions_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Sign out one device. */
        delete: operations["AuthController_revokeSession_v1"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/sessions/revoke-others": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign out every other device. */
        post: operations["AuthController_revokeOthers_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthController_live"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthController_ready"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organization": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["OrganizationController_get_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/branches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PublicBranchesController_list_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/branches/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PublicBranchesController_detail_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/home": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Everything the home page needs for a context, in one request. */
        get: operations["PublicContentController_home_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Feed of published content, newest first (cursor pagination). */
        get: operations["PublicContentController_feed_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/content/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One published item of any type. */
        get: operations["PublicContentController_detail_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Upcoming (soonest first) or past (latest first) events. */
        get: operations["PublicContentController_events_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sermons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sermon library, newest first, with speaker/series/tag filters and search. */
        get: operations["PublicContentController_sermons_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sermons/facets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Speakers, series and tags that have published sermons. */
        get: operations["PublicContentController_facets_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Full-text search across published content and branches. */
        get: operations["PublicContentController_search_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/baptism-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask to be baptised. The chosen branch is notified. */
        post: operations["BaptismController_submit_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        PublicOrganization: {
            name: string;
            shortName: string | null;
            tagline: string | null;
            description: string | null;
            email: string | null;
            phone: string | null;
            websiteUrl: string | null;
            timezone: string;
            locale: string;
            logo: {
                /** Format: uuid */
                id: string;
                url: string;
                width: number | null;
                height: number | null;
                alt: string | null;
                placeholderColor: string | null;
                sources: {
                    url: string;
                    width: number | null;
                    height: number | null;
                }[];
            } | null;
            registrationOpen: boolean;
            baptismRequestsEnabled: boolean;
            socialLinks: {
                [key: string]: string;
            };
        };
        BranchList: {
            items: components["schemas"]["BranchSummary"][];
        };
        BranchSummary: {
            /** Format: uuid */
            id: string;
            slug: string;
            name: string;
            /** @enum {string} */
            type: "MAIN" | "SUB" | "SATELLITE" | "ONLINE";
            city: string | null;
            province: string | null;
            countryCode: string;
            cover: {
                /** Format: uuid */
                id: string;
                url: string;
                width: number | null;
                height: number | null;
                alt: string | null;
                placeholderColor: string | null;
                sources: {
                    url: string;
                    width: number | null;
                    height: number | null;
                }[];
            } | null;
            services: {
                /** Format: uuid */
                id: string;
                /** @enum {string} */
                kind: "SERVICE" | "PRAYER" | "FASTING" | "BIBLE_STUDY" | "YOUTH" | "OTHER";
                title: string | null;
                dayOfWeek: number | null;
                startTime: string | null;
                endTime: string | null;
                recurrenceText: string | null;
                notes: string | null;
                /** Format: date */
                effectiveFrom: string | null;
                /** Format: date */
                effectiveUntil: string | null;
                replacesRegular: boolean;
            }[];
            hasTemporaryChanges: boolean;
        };
        BranchDetail: {
            /** Format: uuid */
            id: string;
            slug: string;
            name: string;
            /** @enum {string} */
            type: "MAIN" | "SUB" | "SATELLITE" | "ONLINE";
            city: string | null;
            province: string | null;
            countryCode: string;
            cover: {
                /** Format: uuid */
                id: string;
                url: string;
                width: number | null;
                height: number | null;
                alt: string | null;
                placeholderColor: string | null;
                sources: {
                    url: string;
                    width: number | null;
                    height: number | null;
                }[];
            } | null;
            services: {
                /** Format: uuid */
                id: string;
                /** @enum {string} */
                kind: "SERVICE" | "PRAYER" | "FASTING" | "BIBLE_STUDY" | "YOUTH" | "OTHER";
                title: string | null;
                dayOfWeek: number | null;
                startTime: string | null;
                endTime: string | null;
                recurrenceText: string | null;
                notes: string | null;
                /** Format: date */
                effectiveFrom: string | null;
                /** Format: date */
                effectiveUntil: string | null;
                replacesRegular: boolean;
            }[];
            hasTemporaryChanges: boolean;
            description: string | null;
            addressLine1: string | null;
            addressLine2: string | null;
            postalCode: string | null;
            latitude: number | null;
            longitude: number | null;
            mapsUrl: string | null;
            phone: string | null;
            email: string | null;
            parent: {
                /** Format: uuid */
                id: string;
                slug: string;
                name: string;
            } | null;
            subBranches: {
                /** Format: uuid */
                id: string;
                slug: string;
                name: string;
            }[];
            schedules: {
                /** Format: uuid */
                id: string;
                /** @enum {string} */
                kind: "SERVICE" | "PRAYER" | "FASTING" | "BIBLE_STUDY" | "YOUTH" | "OTHER";
                title: string | null;
                dayOfWeek: number | null;
                startTime: string | null;
                endTime: string | null;
                recurrenceText: string | null;
                notes: string | null;
                /** Format: date */
                effectiveFrom: string | null;
                /** Format: date */
                effectiveUntil: string | null;
                replacesRegular: boolean;
            }[];
            temporaryChanges: {
                /** Format: uuid */
                id: string;
                /** @enum {string} */
                kind: "SERVICE" | "PRAYER" | "FASTING" | "BIBLE_STUDY" | "YOUTH" | "OTHER";
                title: string | null;
                dayOfWeek: number | null;
                startTime: string | null;
                endTime: string | null;
                recurrenceText: string | null;
                notes: string | null;
                /** Format: date */
                effectiveFrom: string | null;
                /** Format: date */
                effectiveUntil: string | null;
                replacesRegular: boolean;
            }[];
            leaders: {
                /** Format: uuid */
                id: string;
                name: string;
                title: string;
                bio: string | null;
                photo: {
                    /** Format: uuid */
                    id: string;
                    url: string;
                    width: number | null;
                    height: number | null;
                    alt: string | null;
                    placeholderColor: string | null;
                    sources: {
                        url: string;
                        width: number | null;
                        height: number | null;
                    }[];
                } | null;
            }[];
            gallery: {
                /** Format: uuid */
                id: string;
                url: string;
                width: number | null;
                height: number | null;
                alt: string | null;
                placeholderColor: string | null;
                sources: {
                    url: string;
                    width: number | null;
                    height: number | null;
                }[];
                caption: string | null;
            }[];
        };
        HomeResponse: {
            branch: components["schemas"]["BranchSummary"] | null;
            featuredEvent: components["schemas"]["ContentSummary"] | null;
            pinned: components["schemas"]["ContentSummary"][];
            upcomingEvents: components["schemas"]["ContentSummary"][];
            latest: components["schemas"]["ContentSummary"][];
            latestSermon: components["schemas"]["ContentSummary"] | null;
            news: components["schemas"]["ContentSummary"][];
        };
        ContentSummary: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            type: "POST" | "ANNOUNCEMENT" | "NEWS" | "EVENT" | "SERMON" | "BAPTISM";
            slug: string;
            path: string;
            title: string;
            summary: string;
            /** @enum {string} */
            scope: "GLOBAL" | "BRANCH";
            branch: {
                /** Format: uuid */
                id: string;
                slug: string;
                name: string;
            } | null;
            /** Format: date-time */
            publishedAt: string;
            isPinned: boolean;
            isFeatured: boolean;
            cover: {
                /** Format: uuid */
                id: string;
                url: string;
                width: number | null;
                height: number | null;
                alt: string | null;
                placeholderColor: string | null;
                sources: {
                    url: string;
                    width: number | null;
                    height: number | null;
                }[];
            } | null;
            authorName: string | null;
            tags: {
                slug: string;
                name: string;
            }[];
            event: {
                /** Format: date-time */
                startsAt: string;
                /** Format: date-time */
                endsAt: string | null;
                allDay: boolean;
                timezone: string;
                /** @enum {string} */
                category: "SERVICE" | "CONFERENCE" | "BAPTISM" | "YOUTH" | "PRAYER" | "OUTREACH" | "FELLOWSHIP" | "OTHER";
                /** @enum {string} */
                eventStatus: "SCHEDULED" | "POSTPONED" | "CANCELLED";
                venueName: string | null;
            } | null;
            sermon: {
                /** Format: date */
                preachedOn: string;
                speakerName: string | null;
                speakerSlug: string | null;
                seriesTitle: string | null;
                seriesSlug: string | null;
                scripture: string | null;
                durationSeconds: number | null;
                hasAudio: boolean;
                hasVideo: boolean;
            } | null;
            baptism: {
                /** Format: date */
                baptismDate: string | null;
                candidatesCount: number | null;
            } | null;
        };
        ContentPage: {
            items: components["schemas"]["ContentSummary"][];
            nextCursor: string | null;
        };
        ContentDetail: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            type: "POST" | "ANNOUNCEMENT" | "NEWS" | "EVENT" | "SERMON" | "BAPTISM";
            slug: string;
            path: string;
            title: string;
            summary: string;
            /** @enum {string} */
            scope: "GLOBAL" | "BRANCH";
            branch: {
                /** Format: uuid */
                id: string;
                slug: string;
                name: string;
            } | null;
            /** Format: date-time */
            publishedAt: string;
            isPinned: boolean;
            isFeatured: boolean;
            cover: {
                /** Format: uuid */
                id: string;
                url: string;
                width: number | null;
                height: number | null;
                alt: string | null;
                placeholderColor: string | null;
                sources: {
                    url: string;
                    width: number | null;
                    height: number | null;
                }[];
            } | null;
            authorName: string | null;
            tags: {
                slug: string;
                name: string;
            }[];
            event: {
                /** Format: date-time */
                startsAt: string;
                /** Format: date-time */
                endsAt: string | null;
                allDay: boolean;
                timezone: string;
                /** @enum {string} */
                category: "SERVICE" | "CONFERENCE" | "BAPTISM" | "YOUTH" | "PRAYER" | "OUTREACH" | "FELLOWSHIP" | "OTHER";
                /** @enum {string} */
                eventStatus: "SCHEDULED" | "POSTPONED" | "CANCELLED";
                venueName: string | null;
            } | null;
            sermon: {
                /** Format: date */
                preachedOn: string;
                speakerName: string | null;
                speakerSlug: string | null;
                seriesTitle: string | null;
                seriesSlug: string | null;
                scripture: string | null;
                durationSeconds: number | null;
                hasAudio: boolean;
                hasVideo: boolean;
            } | null;
            baptism: {
                /** Format: date */
                baptismDate: string | null;
                candidatesCount: number | null;
            } | null;
            body: string | null;
            /** @enum {string} */
            bodyFormat: "MARKDOWN";
            seoTitle: string | null;
            seoDescription: string | null;
            /** Format: date-time */
            updatedAt: string;
            gallery: {
                /** Format: uuid */
                id: string;
                url: string;
                width: number | null;
                height: number | null;
                alt: string | null;
                placeholderColor: string | null;
                sources: {
                    url: string;
                    width: number | null;
                    height: number | null;
                }[];
                caption: string | null;
            }[];
            eventDetail: {
                /** Format: date-time */
                startsAt: string;
                /** Format: date-time */
                endsAt: string | null;
                allDay: boolean;
                timezone: string;
                /** @enum {string} */
                category: "SERVICE" | "CONFERENCE" | "BAPTISM" | "YOUTH" | "PRAYER" | "OUTREACH" | "FELLOWSHIP" | "OTHER";
                /** @enum {string} */
                eventStatus: "SCHEDULED" | "POSTPONED" | "CANCELLED";
                venueName: string | null;
                statusNote: string | null;
                venueAddress: string | null;
                mapsUrl: string | null;
                onlineUrl: string | null;
                registrationUrl: string | null;
            } | null;
            sermonDetail: {
                /** Format: date */
                preachedOn: string;
                speakerName: string | null;
                speakerSlug: string | null;
                seriesTitle: string | null;
                seriesSlug: string | null;
                scripture: string | null;
                durationSeconds: number | null;
                hasAudio: boolean;
                hasVideo: boolean;
                speaker: {
                    slug: string;
                    name: string;
                    title: string | null;
                } | null;
                series: {
                    slug: string;
                    title: string;
                } | null;
                audio: {
                    url: string;
                    mimeType: string;
                    durationSeconds: number | null;
                    posterUrl: string | null;
                } | null;
                video: {
                    url: string;
                    mimeType: string;
                    durationSeconds: number | null;
                    posterUrl: string | null;
                } | null;
                externalVideoUrl: string | null;
                language: string;
                transcript: string | null;
            } | null;
            baptismDetail: {
                /** Format: date */
                baptismDate: string | null;
                candidatesCount: number | null;
                officiantName: string | null;
                location: string | null;
            } | null;
            related: components["schemas"]["ContentSummary"][];
        };
        SermonFacets: {
            speakers: {
                slug: string;
                name: string;
                title: string | null;
                sermonCount: number;
            }[];
            series: {
                slug: string;
                title: string;
                description: string | null;
                sermonCount: number;
            }[];
            tags: {
                slug: string;
                name: string;
            }[];
        };
        SearchResponse: {
            query: string;
            content: components["schemas"]["ContentSummary"][];
            branches: {
                /** Format: uuid */
                id: string;
                slug: string;
                name: string;
            }[];
        };
        BaptismRequestCreate: {
            branch: string;
            fullName: string;
            /** Format: email */
            email: string;
            phone?: string | null;
            /** Format: date */
            preferredDate?: string | null;
            message?: string | null;
            /** @enum {boolean} */
            consent: true;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AuthController_session_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        user: {
                            /** Format: uuid */
                            id: string;
                            email: string;
                            emailVerified: boolean;
                            firstName: string;
                            lastName: string;
                            displayName: string;
                            avatarUrl: string | null;
                            homeBranch: {
                                /** Format: uuid */
                                id: string;
                                slug: string;
                                name: string;
                            } | null;
                            grants: {
                                /** Format: uuid */
                                branchId: string | null;
                                permissions: string[];
                            }[];
                        } | null;
                    };
                };
            };
        };
    };
    AuthController_csrfToken_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        token: string;
                    };
                };
            };
        };
    };
    AuthController_register_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    password: string;
                    firstName: string;
                    lastName: string;
                    /** @enum {boolean} */
                    acceptTerms: true;
                };
            };
        };
        responses: {
            /** @description Success */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "accepted";
                        message: string;
                    };
                };
            };
        };
    };
    AuthController_verifyEmail_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    token: string;
                };
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        id: string;
                        email: string;
                        emailVerified: boolean;
                        firstName: string;
                        lastName: string;
                        displayName: string;
                        avatarUrl: string | null;
                        homeBranch: {
                            /** Format: uuid */
                            id: string;
                            slug: string;
                            name: string;
                        } | null;
                        grants: {
                            /** Format: uuid */
                            branchId: string | null;
                            permissions: string[];
                        }[];
                    };
                };
            };
        };
    };
    AuthController_resendVerification_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                };
            };
        };
        responses: {
            /** @description Success */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "accepted";
                        message: string;
                    };
                };
            };
        };
    };
    AuthController_login_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    password: string;
                    /** @default false */
                    rememberMe?: boolean;
                };
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        id: string;
                        email: string;
                        emailVerified: boolean;
                        firstName: string;
                        lastName: string;
                        displayName: string;
                        avatarUrl: string | null;
                        homeBranch: {
                            /** Format: uuid */
                            id: string;
                            slug: string;
                            name: string;
                        } | null;
                        grants: {
                            /** Format: uuid */
                            branchId: string | null;
                            permissions: string[];
                        }[];
                    };
                };
            };
        };
    };
    AuthController_logout_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        ok: true;
                    };
                };
            };
        };
    };
    AuthController_forgotPassword_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                };
            };
        };
        responses: {
            /** @description Success */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "accepted";
                        message: string;
                    };
                };
            };
        };
    };
    AuthController_resetPassword_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    token: string;
                    password: string;
                };
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        id: string;
                        email: string;
                        emailVerified: boolean;
                        firstName: string;
                        lastName: string;
                        displayName: string;
                        avatarUrl: string | null;
                        homeBranch: {
                            /** Format: uuid */
                            id: string;
                            slug: string;
                            name: string;
                        } | null;
                        grants: {
                            /** Format: uuid */
                            branchId: string | null;
                            permissions: string[];
                        }[];
                    };
                };
            };
        };
    };
    AuthController_changePassword_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    currentPassword: string;
                    newPassword: string;
                };
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        ok: true;
                    };
                };
            };
        };
    };
    AuthController_listSessions_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: {
                            /** Format: uuid */
                            id: string;
                            current: boolean;
                            userAgent: string | null;
                            ipAddress: string | null;
                            /** Format: date-time */
                            createdAt: string;
                            /** Format: date-time */
                            lastSeenAt: string;
                        }[];
                    };
                };
            };
        };
    };
    AuthController_revokeSession_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        ok: true;
                    };
                };
            };
        };
    };
    AuthController_revokeOthers_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        ok: true;
                    };
                };
            };
        };
    };
    HealthController_live: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "ok";
                    };
                };
            };
        };
    };
    HealthController_ready: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "ok" | "degraded" | "down";
                        checks: {
                            database: {
                                /** @enum {string} */
                                status: "up" | "down";
                                latencyMs: number;
                            };
                            redis: {
                                /** @enum {string} */
                                status: "up" | "down";
                                latencyMs: number;
                            };
                            storage: {
                                /** @enum {string} */
                                status: "up" | "down";
                                latencyMs: number;
                            };
                        };
                    };
                };
            };
        };
    };
    OrganizationController_get_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicOrganization"];
                };
            };
        };
    };
    PublicBranchesController_list_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BranchList"];
                };
            };
        };
    };
    PublicBranchesController_detail_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BranchDetail"];
                };
            };
        };
    };
    PublicContentController_home_v1: {
        parameters: {
            query?: {
                branch?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HomeResponse"];
                };
            };
        };
    };
    PublicContentController_feed_v1: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
                branch?: string;
                types?: string;
                scope?: "all" | "global" | "branch";
                tag?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentPage"];
                };
            };
        };
    };
    PublicContentController_detail_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentDetail"];
                };
            };
        };
    };
    PublicContentController_events_v1: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
                branch?: string;
                scope?: "all" | "global" | "branch";
                when?: "upcoming" | "past";
                category?: "SERVICE" | "CONFERENCE" | "BAPTISM" | "YOUTH" | "PRAYER" | "OUTREACH" | "FELLOWSHIP" | "OTHER";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentPage"];
                };
            };
        };
    };
    PublicContentController_sermons_v1: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
                branch?: string;
                scope?: "all" | "global" | "branch";
                speaker?: string;
                series?: string;
                tag?: string;
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentPage"];
                };
            };
        };
    };
    PublicContentController_facets_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SermonFacets"];
                };
            };
        };
    };
    PublicContentController_search_v1: {
        parameters: {
            query: {
                q: string;
                branch?: string;
                types?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
        };
    };
    BaptismController_submit_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BaptismRequestCreate"];
            };
        };
        responses: {
            /** @description Success */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "accepted";
                        message: string;
                    };
                };
            };
        };
    };
}
